version: '3'

services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            - MARIADB_DATABASE=vendorlistexplorer
            - MARIADB_PASSWORD=CHANGEME
            - MARIADB_USER=vendorlistexplorer
            - MARIADB_RANDOM_ROOT_PASSWORD=1
        volumes:
            - ./db/data:/var/lib/mysql
        networks:
            - back-tier
        ports:
            - 3307:3306
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    flask:
        build: .
        restart: always
        ports:
            - 80:80
        environment:
            - FLASK_APP=main.py
            - 'RUN=flask run --host=0.0.0.0 --port=80'
        command: sh -c './wait-for db:3306 -- bash download_import_vendorlists.sh && flask run --host=0.0.0.0 --port=80'
        networks:
            - back-tier

networks:
  back-tier:
