version: '3'

services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            - MARIADB_DATABASE=vendorlistexplorer
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_USER=vendorlistexplorer
            - MARIADB_RANDOM_ROOT_PASSWORD=1
        volumes:
            - ./db/data:/var/lib/mysql
            - ./docker/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
        ports:
            - 3307:3306
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    flask:
        build: .
        restart: always
        ports:
            - 80:80
        environment:
            - FLASK_APP=main.py
            - 'RUN=flask run --host=0.0.0.0 --port=80'
        volumes:
            - ./vendorlists:/app/vendorlists
        command: sh -c './wait-for db:3306 -- bash download_import_vendorlists.sh && crond && /start.sh'

